### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by menagerie198** [maradotwebp/obsidian-avatar#1]
Hey, nifty little plugin! Could we get a way to do some basic styling? I've rummaged around in the Inspector/Dev Tools, but have been unable to successfully style stuff.

**Comment by maradotwebp** [comment]
You can style the avatar view using a custom CSS snippet file (See how to add that here: https://help.obsidian.md/How+to/Add+custom+styles)

To target the avatar, you can take the classnames from the `<style>` block [in the code](https://github.com/froehlichA/obsidian-avatar/blob/410fa34cd0e87e55ce52ba36af7841fd07a8bc17/src/components/AvatarView.svelte#LL126C1-L126C1) and prefix them with `.block-language-avatar`, like so:

```css
/** Add bigger rounded borders to the avatar image */
.block-language-avatar .avatar {
  border-radius: 100px;
}

/** Make description red */
.block-language-avatar .description {
  color: red;
}
```

If you place the above snippet in a file in `.obsidian/snippets/` and enable your snippet in `Settings => Appearance => CSS Snippets`, you should see the rendered HTML modified :)
