### ISSUE TITLE
Option for avatar on the right?

### ISSUE THREAD

**Issue by gdighton** [maradotwebp/obsidian-avatar#2]
I'd like an option to put the description on the left and the avatar on the right, and maybe set the width of the avatar (ideally as a percentage).

I'd be happy with either plugin settings or some extra fields in the code block. An example of the latter might be

\```avatar
image: foobar.jpg
side: right
width: 25%
description: Loren ipsum dolor sit amet...
\```

Or is this doable with a CSS snippet?

**Comment by maradotwebp** [comment]
Both avatar size and location can now be set via the `size` and `side` property, respectively. As an example:

```yaml
image: foobar.jpg
side: right
size: small
description: A description of your avatar.
```

For more details and other options, see https://github.com/maradotwebp/obsidian-avatar?tab=readme-ov-file#more-options
